version: '2.1'
orbs:
  android: circleci/android@2.5.0
jobs:
  unit-test:
    executor:
      name: android/android-docker
      tag: 2024.04.1
    steps:
      - checkout
      - run:
          name: Grant execute permission to Gradle wrapper
          command: chmod +x ./gradlew
      - android/restore-gradle-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  release-build:
    requires:
      - unit-test
    executor:
      name: android/android-machine
      tag: 2024.04.1
    steps:
      - checkout
      - run:
          name: Grant execute permission to Gradle wrapper
          command: chmod +x ./gradlew
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release
workflows:
  test-and-build:
    jobs:
      - unit-test
      - release-build
